### ISSUE TITLE
How to construct a "Question" parameter for "CreateHIT" operation

### ISSUE THREAD

**Issue by imoonkey** [ctrlcctrlv/mturk-python#4]
I was trying to create an HIT, following the API:
http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITOperation.html

I used the following structure:

html_question  = "<html><body>Some html</body></html>"
r = m.request("CreateHIT", {
    "Question": {"HTMLQuestion":{"HTMLContext":html_question}}, 
    ...(other parameters)
})

Apparently it does not work well, as it keeps return the error:
"Your request parameter Question  has a minimum length of 1. (1421044563382 s)"

I was wondering how should I construct the HTMLQuestion structure to make this work. Thanks!

**Comment by imoonkey** [comment]
It would be good to note this kind of non-trivial parameter structures in the document.
BTW, the following parameter seemed to work well:
{
    "Reward": {"Amount": 1.0, "CurrencyCode": "USD"},
    ...
}

**Comment by alexander-fenster** [comment]
The HTMLQuestion should be an XML.

        price = { 'Amount': hit_price,
                  'CurrencyCode': 'USD'
                }
        question = """<HTMLQuestion xmlns="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2011-11-11/HTMLQuestion.xsd">
                        <HTMLContent><![CDATA[""" + html_content + """]]>
                        </HTMLContent>
                        <FrameHeight>600</FrameHeight>
                      </HTMLQuestion>"""
        hit = { 'Title': hit_title,
                'Description': hit_description,
                'Question': question,
                'Reward': [ price ],
                'AssignmentDurationInSeconds': hit_assignment_duration,
                'LifetimeInSeconds': hit_lifetime,
                'Keywords': hit_keywords,
                'MaxAssignments': hit_max_assignments,
              }

**Comment by ctrlcctrlv** [comment]
@imoonkey @alexander-fenster You're free to write documentation, I haven't put HITs on mTurk for over six months.

All the structures can be created from the Amazon docs though.
