### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ctrlcctrlv** [ctrlcctrlv/mturk-python#8]
I should investigate what, if anything, needs to be done to get this library working in py3k

**Comment by nmalkin** [comment]
Hi!

I added Python 3 support in [my fork](https://github.com/nmalkin/mturk-python): here is [the commit](https://github.com/nmalkin/mturk-python/commit/564d47ead3dcfe557bb8f2589bd21d9ef82844ef).

Happy to send you a pull request!

**Comment by ctrlcctrlv** [comment]
Closed in PR #9.

**Comment by ctrlcctrlv** [comment]
Hope you don't mind, but your branch had other good commits as well so I just merged all of them so users tracking HEAD can get latest fixes.

**Comment by nmalkin** [comment]
Happy to contribute, and thank you for the library! :-)
